### ISSUE TITLE
call a vim function ?

### ISSUE THREAD

**Issue by mckellyln** [Konfekt/vim-alias#6]
Hi,
Thank you for vim-alias.  This is really a question and not an issue.
Is there a way to call a vim function from an alias ?  Something like:
```
:Alias q call QuitFunc()
```

**Comment by Konfekt** [comment]
Perhaps there is merely the escape character after the blank missing? That is
```
:Alias q call\ QuitFunc()
```

**Comment by mckellyln** [comment]
Excellent, thank you.  Sorry I did not realize this.

**Comment by Konfekt** [comment]
Thanks for taking interest. Have a look at https://github.com/Konfekt/vim-alias#examples for all kinds of use cases.
